### ISSUE TITLE
Add live session tracking, multi-session support and fix various bugs

### ISSUE THREAD

**Issue by coolaj86** [dashhive/ledger#11]
https://github.com/digitalcashdev/DashJoin/

- [x] correctly visualize session info
- [x] correct detect, and connect or reconnect to session
- [x] add multi-session support (i.e. for self-test on testnet or faster rounds on mainnet)

Relevant commits (will be squashed later)

- https://github.com/digitalcashdev/DashJoin/commit/8ba93f6 feat: show session info
- https://github.com/digitalcashdev/DashJoin/commit/28b7ff6 wip: debugging dsq vs dsi
- https://github.com/digitalcashdev/DashJoin/commit/e6cd10b feat: track open coinjoin sessions
- https://github.com/digitalcashdev/DashJoin/commit/630dcfc doc: distinguish between P2P and CoinJoin
- https://github.com/digitalcashdev/DashJoin/commit/cf2c2b9 feat: proper multiplexing of CJ pools

**Comment by coolaj86** [comment]
@jojobyte Claiming

Address: XfJh6Wopa2KbLJYZo3vEJNc5cWq2H9yDaX

Deliverables: See above.

Also, about 2/3rds of the work for these was captured live: https://www.youtube.com/playlist?list=PLF5Va8rgg4DGvvOhHkzaUgkCkwWZa7zh-

**Comment by jojobyte** [comment]
@coolaj86 Approved.
